- name: download consul
  get_url:
    url: https://releases.hashicorp.com/consul/1.3.0/consul_1.3.0_linux_amd64.zip
    dest: /usr/local/src/consul.zip

- name: install consul
  command: unzip -o /usr/local/src/consul.zip -d /usr/local/bin
  args:
    creates: /usr/local/bin/consul

- file:
    path: /usr/local/bin/consul
    mode: 0644

- name: copying consul-server script
  copy:
    src: consul-server.sh
    dest: /var/tmp/consul-server.sh
    mode: 0644

- name: copying consul-client script
  copy:
    src: consul-client.sh
    dest: /var/tmp/consul-client.sh
    mode: 0644

- name: copying consul-client config
  copy:
    src: consul.json.client
    dest: /var/tmp/consul.json.client
    mode: 0644

- name: copying consul-server config
  copy:
    src: consul.json.server
    dest: /var/tmp/consul.json.server
    mode: 0644

- name: copying consul script
  copy:
    src: consul.sh
    dest: /var/tmp/consul.sh
    mode: 0644

- name: copying consul service
  copy:
    src: consul.service
    dest: /etc/systemd/system/consul.service

- name: copying web service config
  copy:
    src: web.service.json
    dest: /var/tmp/web.service.json
    mode: 0644

- name: copying LB service config
  copy:
    src: lb.service.json
    dest: /var/tmp/lb.service.json
    mode: 0644
